"""
75x75 chip pipeline: STARsolo + H&E (with on-image barcode markers) -> AnnData -> QC plot.

Differences from st_processing_rew.get_adata_STARsolo:
- No separate brightfield/spot-marker image
- No HE/Spot affine alignment (HE_point/Spot_point are gone)
- Three corner points are picked directly on the H&E image
- Grid is generated by linear interpolation between those corners (same idea
  as get_piexl_coods, but simpler because we don't need 9 region branches)
"""

import os
import time
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt 
import scanpy as sc
import scipy.sparse as sp
from scipy.io import mmread
from anndata import AnnData
import cv2

# ----------------------------------------------------------------------
# Image utilities
# ----------------------------------------------------------------------
def load_image(filename):
    """Load image of any size (handles big histology slides)."""
    from PIL import Image, ImageFile
    ImageFile.LOAD_TRUNCATED_IMAGES = True
    Image.MAX_IMAGE_PIXELS = None
    img = np.array(Image.open(filename))
    if img.ndim == 3 and img.shape[-1] == 4:
        img = img[..., :3]
    elif img.ndim == 2:
        img = cv2.cvtColor(img, cv2.COLOR_GRAY2RGB)
    return img

# ----------------------------------------------------------------------
# Grid generation from three corner points
# ----------------------------------------------------------------------
def get_pixel_grid(corner_X1Y1, corner_Xmax_Y1, corner_X1_Ymax, n_x=75, n_y=75):
    """
    Compute pixel positions for every spot on a regular n_x by n_y grid
    using three corner anchor points on the H&E image.
    根据三个顶点位置推算所有的barcode的位置, 这个芯片有75个barcode在X方向, 75个barcode在Y方向, 
    共5625个barcode. 通过线性插值的方式推算出每个barcode在HE图上的位置.
    
    Parameters
    ----------
    corner_X1Y1 : tuple (col, row)        # X=1, Y=1   (top-left in barcode space)
    corner_Xmax_Y1 : tuple (col, row)     # X=n_x, Y=1 (top-right)
    corner_X1_Ymax : tuple (col, row)     # X=1, Y=n_y (bottom-left)

    Returns
    -------
    pixel_coords : (n_x*n_y, 2) ndarray of int   # (col, row) on the full-res image; 2列的像素坐标;
    grid_coords  : (n_x*n_y, 2) ndarray of int   # (X, Y) barcode coords (1-indexed); 每个barcode的索引位置, 2列分别从1到75;
    spot_pitch   : float                         # mean spot-to-spot pixel distance
    """
    p11 = np.asarray(corner_X1Y1, dtype=float)
    pX1 = np.asarray(corner_Xmax_Y1, dtype=float)
    p1Y = np.asarray(corner_X1_Ymax, dtype=float)

    vec_x = (pX1 - p11) / (n_x - 1)   # one step in +X (column-direction on chip)
    vec_y = (p1Y - p11) / (n_y - 1)   # one step in +Y (row-direction on chip)

    pixel_coords = np.empty((n_x * n_y, 2), dtype=int)
    grid_coords  = np.empty((n_x * n_y, 2), dtype=int)
    k = 0
    for y in range(1, n_y + 1):
        for x in range(1, n_x + 1):
            pt = p11 + (x - 1) * vec_x + (y - 1) * vec_y
            pixel_coords[k] = np.round(pt).astype(int)
            grid_coords[k]  = (x, y)
            k += 1
    
    # np.linalg.norm(vec_x) 表示 sqrt(vec_x[0]^2+vec_x[1]^2) 计算每个barcode在X方向上的像素距离;
    # np.linalg.norm(vec_y) 计算每个barcode在Y方向上的像素距离; 
    # 两者取平均作为最终的spot_pitch, 两个spot之间的平均距离;
    spot_pitch = (np.linalg.norm(vec_x) + np.linalg.norm(vec_y)) / 2
    return pixel_coords, grid_coords, spot_pitch


def visualize_grid(he_image_path, pixel_coords, every=2, save_path=None):
    """
    Overlay the inferred grid on the H&E image for a quick sanity check.
    将所有的barcode网格点都在H&E染色图上展示;

    参数：
    he_image_path: H&E染色图的路径;
    pixel_coords: 每个barcode在HE图上的像素坐标;
    every: 每隔多少个点展示一个点, 默认是2, 也就是展示一半的点;
    """
    # 读取H&E染色图 -> (height, width, 3)
    img = load_image(he_image_path)
    # 创建一个matplotlib画布和坐标轴;
    fig, ax = plt.subplots(figsize=(12, 12))
    # 把H&E图像显示出来, 作为背景图;
    ax.imshow(img)
    # 每隔every个点画一个红色的散点, 代表barcode的位置; s为点大小;
    # 点透明度为0.6, edgecolors='none'表示点没有边框;
    ax.scatter(pixel_coords[::every, 0], pixel_coords[::every, 1],
               s=3, c='red', alpha=0.6, edgecolors='none')
    ax.set_title('Inferred 75x75 grid on H&E')
    # 自动调整图像布局;
    plt.tight_layout()
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight')


# ----------------------------------------------------------------------
# Tissue mask (Otsu, like the original get_HE_mask)
# ----------------------------------------------------------------------
def rgb2gray(rgb):
    return np.dot(rgb[..., :3], [0.2989, 0.5870, 0.1140]).astype('uint8')


def get_HE_mask(img_HE):
    from skimage import filters
    image = rgb2gray(img_HE)
    thresh = filters.threshold_otsu(image)
    _, image_b = cv2.threshold(image, thresh, 250, cv2.THRESH_BINARY_INV)
    mask = np.zeros(image.shape, dtype=np.float32)
    contours, _ = cv2.findContours(image_b, cv2.RETR_EXTERNAL,
                                   cv2.CHAIN_APPROX_NONE)
    if not contours:
        return mask
    areas = [cv2.contourArea(c) for c in contours]
    mask = cv2.drawContours(mask, contours, int(np.argmax(areas)),
                            1, cv2.FILLED)
    return mask

def transform_grid_coords(coords_raw, n_x=75, n_y=75, mode='identity'):
    x = coords_raw[:, 0].astype(int)
    y = coords_raw[:, 1].astype(int)

    if mode == 'identity':
        x2, y2 = x, y

    elif mode == 'swap_xy':
        x2, y2 = y, x

    elif mode == 'rotate_ccw_90':
        x2, y2 = y, n_x + 1 - x

    elif mode == 'rotate_cw_90':
        x2, y2 = n_y + 1 - y, x

    elif mode == 'rotate_180':
        x2, y2 = n_x + 1 - x, n_y + 1 - y

    elif mode == 'flip_x':
        x2, y2 = n_x + 1 - x, y

    elif mode == 'flip_y':
        x2, y2 = x, n_y + 1 - y

    else:
        raise ValueError(f"Unknown transform mode: {mode}")

    return np.column_stack([x2, y2]).astype(int)


# ----------------------------------------------------------------------
# Main builder 从STARsolo和H&E染色图构建一个Visium格式的AnnData对象;
# ----------------------------------------------------------------------
def build_adata_75x75(starsolo_path, barcode_position_file, he_image_path,
                      corner_X1Y1, corner_Xmax_Y1, corner_X1_Ymax,
                      sample_name='sample1', n_x=75, n_y=75,
                      use_em=False, use_filtered=True,
                      species='mouse',
                      compute_mask=True, res_um=None,
                      coord_transform='identity'):
    """
    Build a Visium-style AnnData from STARsolo + H&E (markers on H&E).
    从STARsolo和H&E染色图构建一个Visium格式的AnnData对象;

    Parameters
    ----------
    starsolo_path : str
        Folder containing Gene/raw/ (and Gene/filtered/).
    barcode_position_file : str
        Tab-separated file with at least 3 columns: barcode, X, Y
        (X in 1..n_x, Y in 1..n_y). First column is taken as barcode.
        If you don't have one, see the note below in __main__.
    he_image_path : str
        Full-resolution H&E image with on-image barcode markers.
    corner_X1Y1 / corner_Xmax_Y1 / corner_X1_Ymax : (col, row)
        Pixel positions of three reference spots on the H&E image.
    res_um : float or None
        Physical spot-to-spot distance in microns (used to fill
        scalefactors['microns_pixels']). Optional.
    use_filtered: 使用STARsolo的filtered matrix还是raw matrix, 默认使用filtered;
    use_em: 如果use_filtered=False, 是否使用EM分配的matrix(UniqueAndMult-EM.mtx.gz)还是直接使用raw的matrix.mtx.gz, 默认不使用EM分配的matrix;
    """
    t0 = time.time()
    sub = 'filtered' if use_filtered else 'raw'

    if use_em and not use_filtered:
        mtx_path = os.path.join(starsolo_path, f'Gene/{sub}/UniqueAndMult-EM.mtx.gz')
    else:
        mtx_path = os.path.join(starsolo_path, f'Gene/{sub}/matrix.mtx.gz')
    bc_path = os.path.join(starsolo_path, f'Gene/{sub}/barcodes.tsv')
    feat_path = os.path.join(starsolo_path, f'Gene/{sub}/features.tsv')

    # 1) Read STARsolo matrix (genes x cells -> cells x genes)
    print(f'[{time.strftime("%H:%M:%S")}] Reading {os.path.basename(mtx_path)}')
    X = mmread(mtx_path).astype(int).T.tocsr()
    df_bc = pd.read_csv(bc_path, sep='\t', header=None, names=['barcode'])
    df_ft = pd.read_csv(feat_path, sep='\t', header=None,
                        names=['gene_id', 'gene_symbol', 'feature_type'])

    # 2) Map every barcode to (X, Y)
    print(f'[{time.strftime("%H:%M:%S")}] Mapping barcodes to (X, Y)')

    # 如果你的文件是tab分隔, 用sep='\t'; 默认是有表头的, 用header=0; 如果没有表头, 用header=None并提供names参数;
    bc_pos = pd.read_csv(barcode_position_file, sep='\t', engine='python')
    # 清理列名
    bc_pos.columns = [c.strip() for c in bc_pos.columns]

    # 判断barcode list是否有这几列;
    required_cols = {"barcode", "x", "y"}
    missing_cols = required_cols - set(bc_pos.columns)
    if len(missing_cols) != 0:
        raise ValueError(f"These columns are missing: {missing_cols}")

    # 把小写 x/y 改成后面代码需要的大写 X/Y
    bc_pos = bc_pos.rename(columns={
        'x': 'X',
        'y': 'Y'
    })

    # 只保留 barcode -> X/Y 坐标
    bc_pos = bc_pos.set_index('barcode')[['X', 'Y']].astype(int)

    # 只保留在bc_pos中有坐标的barcode;
    keep = df_bc['barcode'].isin(bc_pos.index).values
    # 同步过滤表达矩阵和barcode表;
    X = X[keep, :]
    df_bc = df_bc.loc[keep].reset_index(drop=True)
    # 按照过滤后的barcode顺序提取坐标;
    coords_raw = bc_pos.loc[df_bc['barcode'].values, ['X', 'Y']].to_numpy()
    
    # 坐标方向变换;
    coords = transform_grid_coords(
        coords_raw, n_x=n_x, n_y=n_y, 
        mode=coord_transform
    )

    # 3) Compute pixel grid for every (X, Y) on the chip
    print(f'[{time.strftime("%H:%M:%S")}] Computing pixel grid')
    pix_full, grid_full, spot_pitch = get_pixel_grid(
        corner_X1Y1, corner_Xmax_Y1, corner_X1_Ymax, n_x=n_x, n_y=n_y)
    # 建立一个字典, 把芯片坐标映射到像素坐标;
    # 比如: (np.int64(60), np.int64(75)): array([13017, 16154])
    grid_to_pix = {tuple(g): p for g, p in zip(grid_full, pix_full)}
    # 根据每个barcode的芯片坐标(X, Y), 查找它在H&E图上的像素坐标;
    pix_obs = np.array([grid_to_pix[(int(x), int(y))] for x, y in coords])

    # 4) H&E image, low/hi-res versions, scalefactors
    print(f'[{time.strftime("%H:%M:%S")}] Loading H&E image')
    he = load_image(he_image_path)
    # 获取H&E原图尺寸;
    h_full, w_full = he.shape[:2]
    # 把H&E图最长边缩放到2000 pixels;
    hires_scalef = round(2000 / max(h_full, w_full), 8)
    # 把H&E图最长边缩放到600 pixels;
    lowres_scalef = round(600 / max(h_full, w_full), 8)
    # 生成hires/lowres图像;
    hires_img  = cv2.resize(he, (int(w_full * hires_scalef),
                                  int(h_full * hires_scalef)))
    lowres_img = cv2.resize(he, (int(w_full * lowres_scalef),
                                  int(h_full * lowres_scalef)))

    # 5) in_tissue from Otsu mask
    if compute_mask:
        mask = get_HE_mask(he)
        # 判断每个spot是否落在tissue上;
        in_tissue = mask[pix_obs[:, 1], pix_obs[:, 0]].astype(int).astype(str)
    else:
        # 如果不计算mask, 就默认所有spot都在组织上;
        in_tissue = np.array(['1'] * len(pix_obs))

    # 6) Assemble AnnData
    obs = pd.DataFrame({
        'sample_id': sample_name,
        'barcode'  : df_bc['barcode'].values,
        'Spot_col' : coords[:, 0],
        'Spot_row' : coords[:, 1],
        'in_tissue': in_tissue,
    }, index=df_bc['barcode'].values)

    var = pd.DataFrame(
        {'gene_symbol': df_ft['gene_symbol'].values,
         'feature_type': df_ft['feature_type'].values},
        index=df_ft['gene_id'].values
    )

    scalefactors = {
        'tissue_hires_scalef' : float(hires_scalef),
        'tissue_lowres_scalef': float(lowres_scalef),
        'spot_diameter_fullres': float(spot_pitch),
    }

    # 如果用户提供了真实物理间距res_um, 就计算微米和像素的关系; 
    if res_um is not None:
        scalefactors['microns_pixels'] = float(res_um / spot_pitch)

    adata = AnnData(
        X=X, obs=obs, var=var,
        obsm={'spatial': pix_obs},
        uns={'spatial': {sample_name: {
            'images': {'hires': hires_img, 'lowres': lowres_img},
            'scalefactors': scalefactors,
        }}}
    )
    # var_names换成symbol_id;
    adata.var['gene_id'] = adata.var_names
    adata.var_names = adata.var['gene_symbol'].astype(str)
    adata.var_names_make_unique()
    adata.var.index.name = None

    # 7) QC
    if species == 'mouse':
        adata.var['mt']   = adata.var['gene_symbol'].str.startswith('mt-')
        adata.var['ribo'] = adata.var['gene_symbol'].str.startswith(('Rps', 'Rpl'))
        adata.var['hb']   = adata.var['gene_symbol'].str.contains(r'^Hb[^p]', regex=True)
    else:  # human / pig / etc default
        adata.var['mt']   = adata.var['gene_symbol'].str.startswith('MT-')
        adata.var['ribo'] = adata.var['gene_symbol'].str.startswith(('RPS', 'RPL'))
        adata.var['hb']   = adata.var['gene_symbol'].str.contains(r'^HB[^P]', regex=True)
    sc.pp.calculate_qc_metrics(adata, qc_vars=['mt', 'ribo', 'hb'], inplace=True)

    in_tis = adata.obs['in_tissue'] == '1'
    print(f"[{time.strftime('%H:%M:%S')}] Done in {time.time()-t0:.1f}s")
    print(f"  total spots         : {adata.n_obs}")
    print(f"  spots in tissue     : {in_tis.sum()}  "
          f"({100*in_tis.mean():.1f}%)")
    if in_tis.sum():
        print(f"  median UMIs (tissue): "
              f"{np.median(adata.obs.total_counts[in_tis]):.0f}")
        print(f"  median genes(tissue): "
              f"{np.median(adata.obs.n_genes_by_counts[in_tis]):.0f}")
    return adata

# ----------------------------------------------------------------------
# Plotting (reproduces the two-panel QC figure)
# ----------------------------------------------------------------------
def plot_qc_spatial(adata, save_path=None, cmap='Spectral_r',
                    keys=('total_counts', 'n_genes_by_counts'),
                    point_size=15, dpi=300, show=False):
    """Two-panel spatial QC plot."""
    fig, axes = plt.subplots(1, len(keys), figsize=(7 * len(keys), 6))

    if len(keys) == 1:
        axes = [axes]

    for ax, k in zip(axes, keys):
        sc.pl.embedding(
            adata, basis='spatial',
            color=k, cmap=cmap, ax=ax,
            show=False, size=point_size, frameon=True
        )
        ax.set_aspect('equal')
        ax.invert_yaxis()

    plt.tight_layout()

    if save_path:
        plt.savefig(save_path, dpi=dpi, bbox_inches='tight')
        print(f"Saved QC plot to: {save_path}")

    if show:
        plt.show()
    else:
        plt.close(fig)

    return fig


def plot_qc_on_he(adata, sample_name="sample1", save_path=None, img_key='hires',
                  cmap='Spectral_r', keys=('total_counts', 'n_genes_by_counts'),
                  size=1.2, alpha=0.9, alpha_img=1.0, dpi=300
                  ):
    """
    Overlay spatial QC values on the H&E image using scanpy spatial plotting.
    """
    fig, axes = plt.subplots(1, len(keys), figsize=(7 * len(keys), 6))
    if len(keys) == 1:
        axes = [axes]

    for ax, k in zip(axes, keys):
        sc.pl.spatial(
            adata, color=k, library_id=sample_name,
            img_key=img_key, 
            cmap=cmap, ax=ax, show=False, size=size, alpha=alpha,  
            alpha_img=alpha_img, frameon=False, title=k
        )

    plt.tight_layout()

    if save_path:
        plt.savefig(save_path, dpi=dpi, bbox_inches='tight')
        print(f"Saved to: {save_path}")

    plt.close(fig)
    return fig


def plot_qc_violin(
    adata,
    save_path=None,
    keys=('total_counts', 'n_genes_by_counts', 'pct_counts_mt'),
    titles=('UMI / spot', 'Genes / spot', '% mitochondrial'),
    dpi=300,
    show=False
):
    """
    Plot QC violin plots for spatial transcriptomics data.

    Parameters
    ----------
    adata : AnnData
        AnnData object with QC metrics calculated.
    save_path : str or None
        Output figure path.
    keys : tuple
        QC metrics in adata.obs.
    titles : tuple
        Titles for each violin plot.
    dpi : int
        Figure dpi.
    show : bool
        Whether to show figure.
    """

    for k in keys:
        if k not in adata.obs.columns:
            raise ValueError(f"{k} is not found in adata.obs. Please run sc.pp.calculate_qc_metrics first.")

    fig, axes = plt.subplots(1, len(keys), figsize=(5 * len(keys), 4))

    if len(keys) == 1:
        axes = [axes]

    for ax, key, title in zip(axes, keys, titles):
        sc.pl.violin(
            adata,
            keys=key,
            jitter=0.4,
            ax=ax,
            show=False
        )
        ax.set_title(title)

    plt.tight_layout()

    if save_path is not None:
        plt.savefig(save_path, dpi=dpi, bbox_inches='tight')
        print(f"Saved QC violin plot to: {save_path}")

    if show:
        plt.show()
    else:
        plt.close(fig)

    return fig


def plot_qc_scatter(
    adata,
    save_path=None,
    dpi=300,
    show=False
):
    """
    Plot QC scatter plots:
    total_counts vs n_genes_by_counts,
    total_counts vs pct_counts_mt.
    """

    required = {'total_counts', 'n_genes_by_counts', 'pct_counts_mt'}
    missing = required - set(adata.obs.columns)

    if missing:
        raise ValueError(f"These QC columns are missing: {missing}")

    fig, axes = plt.subplots(1, 2, figsize=(10, 4))

    sc.pl.scatter(
        adata,
        x='total_counts',
        y='n_genes_by_counts',
        ax=axes[0],
        show=False
    )
    axes[0].set_title('UMI vs Genes')

    sc.pl.scatter(
        adata,
        x='total_counts',
        y='pct_counts_mt',
        ax=axes[1],
        show=False
    )
    axes[1].set_title('UMI vs % mitochondrial')

    plt.tight_layout()

    if save_path is not None:
        plt.savefig(save_path, dpi=dpi, bbox_inches='tight')
        print(f"Saved QC scatter plot to: {save_path}")

    if show:
        plt.show()
    else:
        plt.close(fig)

    return fig


def run_downstream_analysis(
    adata, n_top_genes=3000, n_pcs=30, n_neighbors=15, resolution=0.5,
    cluster_key='leiden', use_in_tissue=True, copy=True
):
    """
    Run standard Scanpy downstream analysis:
    QC filtering -> normalization -> HVG selection -> PCA -> neighbors -> UMAP -> Leiden clustering.

    Parameters
    ----------
    adata : AnnData
        AnnData object generated by build_adata_75x75.
    n_top_genes : int
        Number of highly variable genes.
    n_pcs : int
        Number of principal components used for neighbor graph.
    n_neighbors : int
        Number of neighbors for neighborhood graph.
    resolution : float
        Leiden clustering resolution.
    cluster_key : str
        Column name in adata.obs to store cluster labels.
    use_in_tissue : bool
        If True, only keep spots with in_tissue == '1' for downstream analysis.
    copy : bool
        If True, return a new AnnData object.

    Returns
    -------
    adata : AnnData
        Processed AnnData with PCA, UMAP and Leiden clustering.
    """

    if copy:
        adata = adata.copy()

    # 1) Optional: only keep tissue spots
    if use_in_tissue and 'in_tissue' in adata.obs.columns:
        adata = adata[adata.obs['in_tissue'].astype(str) == '1'].copy()

    # 2) Basic filtering
    sc.pp.filter_cells(adata, min_genes=200)
    sc.pp.filter_genes(adata, min_cells=3)

    # 3) Save raw counts before normalization
    adata.layers['counts'] = adata.X.copy()

    # 4) Normalize and log transform
    sc.pp.normalize_total(adata, target_sum=1e4)
    sc.pp.log1p(adata)

    # 5) Store normalized log data in raw for marker visualization
    adata.raw = adata

    # 6) Highly variable genes
    sc.pp.highly_variable_genes(
        adata, n_top_genes=n_top_genes, flavor='seurat'
    )

    # 7) PCA using HVGs
    sc.pp.scale(adata, max_value=10, zero_center=False)
    sc.tl.pca(
        adata, n_comps=n_pcs, mask_var='highly_variable', svd_solver='arpack'
    )

    # 8) Neighbor graph, UMAP, Leiden clustering
    sc.pp.neighbors(
        adata, n_neighbors=n_neighbors, n_pcs=n_pcs
    )

    sc.tl.umap(adata)

    sc.tl.leiden(
        adata, resolution=resolution, key_added=cluster_key
    )

    return adata

def find_marker_genes(
    adata, cluster_key='leiden', method='wilcoxon',
    pts=True, n_genes=100, save_path=None
):
    """
    Find marker genes for each cluster using scanpy.tl.rank_genes_groups.

    Parameters
    ----------
    adata : AnnData
        Processed AnnData after clustering.
    cluster_key : str
        Cluster column in adata.obs.
    method : str
        Method for marker detection: 'wilcoxon', 't-test', 'logreg'.
    pts : bool
        Whether to calculate fraction of cells/spots expressing genes.
    n_genes : int
        Number of genes to export per cluster.
    save_path : str or None
        If provided, save marker table as csv.

    Returns
    -------
    marker_df : pandas.DataFrame
        Marker gene table.
    """

    if cluster_key not in adata.obs.columns:
        raise ValueError(f"{cluster_key} is not found in adata.obs")

    sc.tl.rank_genes_groups(
        adata,
        groupby=cluster_key,
        method=method,
        pts=pts
    )

    marker_df = sc.get.rank_genes_groups_df(
        adata,
        group=None
    )

    if n_genes is not None:
        marker_df = (
            marker_df
            .groupby('group', group_keys=False)
            .head(n_genes)
        )

    if save_path is not None:
        marker_df.to_csv(save_path, index=False)
        print(f"Saved marker genes to: {save_path}")

    return marker_df

def plot_clusters(
    adata, cluster_key='leiden', sample_name='sample1',
    out_dir='.', point_size=20, spatial_size=1.2, dpi=300
):
    """
    Plot UMAP clustering, spatial clustering, and spatial clustering on H&E.

    Parameters
    ----------
    adata : AnnData
        Processed AnnData after clustering.
    cluster_key : str
        Cluster column in adata.obs.
    sample_name : str
        Library/sample name used in adata.uns['spatial'].
    out_dir : str
        Output directory.
    point_size : float
        Point size for UMAP/spatial embedding.
    spatial_size : float
        Spot size for sc.pl.spatial.
    dpi : int
        Figure DPI.
    """
    
    os.makedirs(out_dir, exist_ok=True)

    # UMAP cluster plot
    sc.pl.umap(
        adata, color=cluster_key, frameon=False, show=False
    )
    plt.savefig(
        os.path.join(out_dir, f'{sample_name}_umap_{cluster_key}.png'),
        dpi=dpi, bbox_inches='tight'
    )
    plt.close()

    # Spatial cluster plot without H&E background
    sc.pl.embedding(
        adata, basis='spatial', color=cluster_key, size=point_size,
        frameon=True, show=False
    )
    plt.gca().set_aspect('equal')
    plt.gca().invert_yaxis()
    plt.savefig(
        os.path.join(out_dir, f'{sample_name}_spatial_{cluster_key}.png'),
        dpi=dpi,
        bbox_inches='tight'
    )
    plt.close()

    # Spatial cluster plot on H&E
    if 'spatial' in adata.uns and sample_name in adata.uns['spatial']:
        sc.pl.spatial(
            adata,
            color=cluster_key,
            library_id=sample_name,
            img_key='hires',
            size=spatial_size,
            frameon=False,
            show=False
        )
        plt.savefig(
            os.path.join(out_dir, f'{sample_name}_HE_{cluster_key}.png'),
            dpi=dpi,
            bbox_inches='tight'
        )
        plt.close()

def plot_marker_genes(
    adata,
    marker_df,
    cluster_key='leiden',
    sample_name='sample1',
    out_dir='.',
    top_n=5,
    dpi=300
):
    """
    Plot top marker genes using dotplot and spatial plots.

    Parameters
    ----------
    adata : AnnData
        Processed AnnData.
    marker_df : pandas.DataFrame
        Marker gene table returned by find_marker_genes.
    cluster_key : str
        Cluster column in adata.obs.
    sample_name : str
        Library/sample name.
    out_dir : str
        Output directory.
    top_n : int
        Number of top marker genes per cluster to visualize.
    dpi : int
        Figure DPI.
    """
    out_dir = os.path.join(out_dir, 'Downstreamfigures')
    os.makedirs(out_dir, exist_ok=True)

    # Select top marker genes from each cluster
    top_markers = (
        marker_df
        .groupby('group', group_keys=False)
        .head(top_n)['names']
        .dropna()
        .unique()
        .tolist()
    )

    if len(top_markers) == 0:
        print("No marker genes found for plotting.")
        return

    # Dotplot
    sc.pl.dotplot(
        adata,
        var_names=top_markers,
        groupby=cluster_key,
        standard_scale='var',
        show=False
    )
    plt.savefig(
        os.path.join(out_dir, f'{sample_name}_top_marker_dotplot.png'),
        dpi=dpi,
        bbox_inches='tight'
    )
    plt.close()

    # Spatial plot for top marker genes
    for gene in top_markers:
        if gene not in adata.var_names:
            continue

        sc.pl.embedding(
            adata,
            basis='spatial',
            color=gene,
            cmap='Spectral_r',
            size=20,
            frameon=True,
            show=False
        )
        plt.gca().set_aspect('equal')
        plt.gca().invert_yaxis()
        plt.savefig(
            os.path.join(out_dir, f'{sample_name}_spatial_marker_{gene}.png'),
            dpi=dpi,
            bbox_inches='tight'
        )
        plt.close()

        if 'spatial' in adata.uns and sample_name in adata.uns['spatial']:
            sc.pl.spatial(
                adata,
                color=gene,
                library_id=sample_name,
                img_key='hires',
                cmap='Spectral_r',
                size=1.2,
                frameon=False,
                show=False
            )
            plt.savefig(
                os.path.join(out_dir, f'{sample_name}_HE_marker_{gene}.png'),
                dpi=dpi,
                bbox_inches='tight'
            )
            plt.close()

def run_full_scanpy_pipeline(
    adata,
    sample_name='sample1',
    out_dir='.',
    n_top_genes=3000,
    n_pcs=30,
    n_neighbors=15,
    resolution=0.5,
    cluster_key='leiden',
    use_in_tissue=True,
    marker_method='wilcoxon',
    top_marker_genes=100,
    plot_top_n_marker=5,
    save_h5ad=True
):
    """
    Full downstream Scanpy pipeline:
    preprocessing, dimensionality reduction, clustering, marker detection and plotting.

    Returns
    -------
    adata_processed : AnnData
        Processed AnnData.
    marker_df : pandas.DataFrame
        Marker gene table.
    """

    os.makedirs(out_dir, exist_ok=True)

    print("Running downstream analysis...")
    adata_processed = run_downstream_analysis(
        adata,
        n_top_genes=n_top_genes,
        n_pcs=n_pcs,
        n_neighbors=n_neighbors,
        resolution=resolution,
        cluster_key=cluster_key,
        use_in_tissue=use_in_tissue,
        copy=True
    )

    print("Plotting clusters...")
    plot_clusters(
        adata_processed,
        cluster_key=cluster_key,
        sample_name=sample_name,
        out_dir=out_dir
    )

    print("Finding marker genes...")
    marker_df = find_marker_genes(
        adata_processed,
        cluster_key=cluster_key,
        method=marker_method,
        n_genes=top_marker_genes,
        save_path=os.path.join(out_dir, f'{sample_name}_{cluster_key}_marker_genes.csv')
    )

    print("Plotting marker genes...")
    plot_marker_genes(
        adata_processed,
        marker_df,
        cluster_key=cluster_key,
        sample_name=sample_name,
        out_dir=out_dir,
        top_n=plot_top_n_marker
    )

    if save_h5ad:
        h5ad_path = os.path.join(out_dir, f'{sample_name}_processed.h5ad')
        adata_processed.write_h5ad(h5ad_path)
        print(f"Saved processed AnnData to: {h5ad_path}")

    print("Done.")
    return adata_processed, marker_df


# ----------------------------------------------------------------------
# Example usage
# ----------------------------------------------------------------------
if __name__ == '__main__':
    SAMPLE = 'sample1'
    STARSOLO_DIR = '/data/workdir/panw/py_singlecell/Spatial/MAGIC-seq/bingqi_Decoderseq/DCseqformalMB_S1_L001_Solo.out'
    BARCODE_POS  = '/data/workdir/panw/py_singlecell/Spatial/MAGIC-seq/bingqi_Decoderseq/7.5mm_barcode_coordinate.txt'
    HE_IMAGE     = '/data/workdir/panw/py_singlecell/Spatial/MAGIC-seq/bingqi_Decoderseq/MyflipTest.tif'
    outPut       = '/data/workdir/panw/py_singlecell/Spatial/MAGIC-seq/bingqi_Decoderseq/pictures'
    os.makedirs(f'{outPut}', exist_ok=True)
    # 这里给的坐标和barcode不是很清楚, 通过最后结果判断是翻转了;
    # 默认不做操作的话用identity, 这个示例数据需要翻转一下;
    coord_transform_mode = 'flip_y' # identity/swap_xy/rotate_ccw_90/rotate_cw_90/...

    # ----- Step 1: get the three corner pixel positions ---------------
    # 获取左上, 右上, 左下的三个像素的位置;
    corner_X1Y1  = (480, 464)    # top-left
    corner_X75Y1 = (16144, 496)  # top-right
    corner_X1Y75 = (528, 16128)  # bottom-left

    # ----- Step 2 (optional): sanity-check the grid -------------------
    pix_full, _, _ = get_pixel_grid(corner_X1Y1, corner_X75Y1, corner_X1Y75)
    visualize_grid(HE_IMAGE, pix_full, every=1,
                   save_path=f'{outPut}/{SAMPLE}_grid_check.png')

    # ----- Step 3: build AnnData --------------------------------------
    adata = build_adata_75x75(
        starsolo_path=STARSOLO_DIR, barcode_position_file=BARCODE_POS, he_image_path=HE_IMAGE,
        corner_X1Y1=corner_X1Y1, corner_Xmax_Y1=corner_X75Y1, corner_X1_Ymax=corner_X1Y75,
        sample_name=SAMPLE, n_x=75, n_y=75, species='mouse',
        coord_transform=coord_transform_mode
    )

    # ----- Step 4: the two-panel QC plot ------------------------------
    plot_qc_spatial(adata, save_path=f'{outPut}/{SAMPLE}_qc_spatial.png')
    plot_qc_on_he(adata, save_path=f'{outPut}/{SAMPLE}_qc_on_HE.png')
    plot_qc_violin(adata, save_path=f'{outPut}/{SAMPLE}_qc_violin.png')
    plot_qc_scatter(adata, save_path=f'{outPut}/{SAMPLE}_qc_scatter.png')
    
    adata_processed, marker_df = run_full_scanpy_pipeline(
        adata, sample_name=SAMPLE, out_dir=outPut,
        n_top_genes=3000, n_pcs=30, n_neighbors=15, resolution=0.5,
        cluster_key='leiden', use_in_tissue=True, marker_method='wilcoxon',
        top_marker_genes=30, plot_top_n_marker=5, save_h5ad=True
    )    

    # save for downstream
    adata.write_h5ad(f'{outPut}/{SAMPLE}.h5ad')











